src/authentication/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'auth'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.login_user, name='login'),
    path('send-email-verification/', views.send_email_verification, name='send-email-verification'),
    path('verify/<str:token>/', views.verify_email, name='verify'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset/', views.CustomPasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         views.CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-done/',
         views.CustomPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-complete/',
         views.CustomPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

src/jobs/urls.py
from django.urls import path

from jobs import views

app_name = 'jobs'
urlpatterns = [
    # ex: /job_offers/5
    path('job_offers/<int:pk>/', views.JobOffersView.as_view(), name='job_offers'),
    path('', views.MainView.as_view(), name='main'),
    path('profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('company/<int:pk>/', views.CompanyView.as_view(), name='company'),
    # ex: /edit_profile
    path('edit_profile/', views.edit_profile_view, name='edit_profile'),
    # ex: /edit_profile/delete_skill/5
    path('edit_profile/delete_skill/<skill_id>/', views.delete_skill, name='delete_skill'),
    # ex: /edit_profile/delete_educational_background/5
    path('edit_profile/delete_educational_background/<educational_background_id>/',
         views.delete_educational_background, name='delete_educational_background'),
    path('edit_profile/alt_email/add/', views.add_alt_email, name='add_alt_email'),
    path('edit_profile/alt_email/delete/<int:alt_email_pk>/',
         views.delete_alt_email,
         name='delete_alt_email'),
    path('send-email-verification/<int:email_pk>/',
         views.send_email_verification,
         name='send-email-verification'),
    path('verify/<str:token>/', views.verify, name='verify'),
    # ex: /job_offers/5/apply
    path('job_offers/<int:pk>/apply/', views.apply, name='apply'),
    path('create_resume/', views.create_resume, name='create_resume'),
    path('edit_inform_joboffer/<int:job_offer_pk>/', views.edit_inform_jobOffer, name='edit_inform_job')

]

src/website/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('i18n/set_language/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('jobs.urls')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = 'website.views.error_404'

src/jobs/models.py
from django.utils.translation import get_language
from jobs.templatetags.extra_tags import translate_numbers
from django.db import models, IntegrityError
from authentication.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.crypto import get_random_string
from django.utils.translation import gettext_lazy as _
from jobs.managers import EnabledManager, JobQuerySet
from django.core.files.storage import FileSystemStorage
from website.settings import MEDIA_URL, MEDIA_ROOT


class EducationalLevel(models.TextChoices):
    DIPLOMA = 'DI', _('High School Diploma')
    ASSOCIATE = 'A', _('Associate Degree')
    BACHELORS_DEGREE = 'B', _('Bachelors Degree')
    MASTERS_DEGREE = 'M', _('Masters Degree')
    DOCTORAL_DEGREE = 'DO', _('Doctoral Degree')
    POSTDOCTORAL_DEGREE = 'P', _('Post Doctoral Degree')
    OTHERS = 'O', _('Others')

    @staticmethod
    def _get_educational_levels_order_list():
        return [EducationalLevel.OTHERS,
                EducationalLevel.DIPLOMA,
                EducationalLevel.ASSOCIATE,
                EducationalLevel.BACHELORS_DEGREE,
                EducationalLevel.MASTERS_DEGREE,
                EducationalLevel.DOCTORAL_DEGREE,
                EducationalLevel.POSTDOCTORAL_DEGREE]

    def get_le_educational_levels(self):
        return EducationalLevel._get_educational_levels_order_list()[:self.order_index + 1]

    def get_ge_educational_levels(self):
        return EducationalLevel._get_educational_levels_order_list()[self.order_index:]

    @property
    def order_index(self):
        return EducationalLevel._get_educational_levels_order_list().index(self)


class CategoryJob(models.TextChoices):
    DataScience_and_Analytics = 'DA', _('Data')
    Design_and_UX = 'DU', _('Design and UX')
    Engineering = 'E', _('Engineering')
    Finance_and_Accounting = 'FA', _('Finance and Accounting')
    Human_Resources = 'HR', _('Human Resources')
    Marketing_and_Communications = 'MC', _('Marketing and Communications')
    Operation = 'O', _('Operation')
    Product = 'P', _('Product')
    Sales = 'S', _('Sales')
    Other = 'OT', _('Other')


class Company(models.Model):
    name = models.CharField(max_length=255, unique=True)
    address = models.TextField(blank=True)
    logo = models.ImageField(upload_to='images', blank=True)
    description = models.TextField(blank=True)
    link = models.URLField(max_length=200)
    telephone_number = models.CharField(max_length=12)

    class Meta:
        verbose_name_plural = "Companies"

    def __str__(self):
        return self.name


class Skill(models.Model):
    """
    Each skills consists of a title.
    UserProfile has ManyToMany relationship with fields.
    """
    title = models.CharField(max_length=80, primary_key=True)

    def __str__(self):
        return self.title


class JobOffer(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=500, blank=True)
    salary = models.IntegerField(blank=True, null=True)
    minimum_work_experience = models.IntegerField(default=0)
    CHOICES_TIME = [
        ('full_time', _('full time')),
        ('part_time', _('part time')),
    ]

    type_of_cooperation = models.CharField(choices=CHOICES_TIME, max_length=10)
    minimum_degree = models.CharField(max_length=2, choices=EducationalLevel.choices, null=True, blank=True)
    skills_required = models.ManyToManyField(Skill, blank=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="job_offers")
    city = models.CharField(max_length=100, null=True, blank=True)
    is_enabled = models.BooleanField(default=True, db_index=True)
    category = models.CharField(max_length=2, choices=CategoryJob.choices, null=True, blank=True)
    users_tagged_job = models.ManyToManyField(CustomUser, blank=True, related_name='tagged_jobs')

    objects = JobQuerySet.as_manager()
    enabled = EnabledManager()

    def __str__(self):
        return self.title

    def send_offer_suggestion_email_to_qualified_users(self, *exceptional_users):
        """
        Calling Situation:
        This Function Should be called after saving JobOffer and setting it's m2m and foreign key relations
        """
        for user in CustomUser.objects.qualified_users_for_offer(self, *exceptional_users):
            from jobs.tasks import send_offer_suggestion_email
            send_offer_suggestion_email.delay(user.pk, self.pk)

    def send_inform_email_to_tagged_users(self):
        from jobs.tasks import send_tagged_offer_email
        for user in self.users_tagged_job.all():
            send_tagged_offer_email.delay(user.pk, self.pk)
        self.clear_tagged_job_for_users()

    def clear_tagged_job_for_users(self):
        self.users_tagged_job.clear()

    class Meta:
        ordering = ['-is_enabled']


class UserProfile(models.Model):
    """
    UserProfile model, first_name & last_name of users are stored in CustomUser,
    other personal fields are stored here.
    """

    class MilitaryServiceStatus(models.TextChoices):
        CONSCRIPT = 'CO', _('Conscript')
        EDUCATIONAL_EXEMPTION = 'EE', _('Educational Exemption')
        EXEMPT = 'E', _('Exempt')
        DISCHARGE = 'D', _('Discharge')

    class Gender(models.TextChoices):
        MALE = 'M', _('Male')
        FEMALE = 'F', _('Female')
        OTHERS = 'O', _('Other')

    class MaritalStatus(models.TextChoices):
        SINGLE = 'S', _('Single')
        MARRIED = 'M', _('Married')

        # WIDOWED = 'W', _('Widowed')
        # DIVORCED = 'D', _('Divorced')
        # SEPARATED = 'S', _('Separated')

    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, related_name="profile")
    mobile_number = models.CharField(max_length=11, blank=True, null=True, verbose_name=_('Mobile number'))
    phone_number = models.CharField(max_length=11, blank=True, null=True, verbose_name=_('Phone number'))
    address = models.CharField(max_length=280, blank=True, null=True, verbose_name=_('Address'))
    military_service_status = models.CharField(max_length=2,
                                               choices=MilitaryServiceStatus.choices,
                                               blank=True, null=True,
                                               verbose_name=_('Military service status')
                                               )
    gender = models.CharField(max_length=1,
                              choices=Gender.choices,
                              blank=True, null=True,
                              verbose_name=_('Gender')
                              )
    marital_status = models.CharField(max_length=1,
                                      choices=MaritalStatus.choices,
                                      blank=True, null=True,
                                      verbose_name=_('Marital status')
                                      )
    city_of_residence = models.CharField(max_length=80, null=True, blank=True, verbose_name=_('City of residence'))
    bio = models.TextField(null=True, blank=True, verbose_name=_('Bio'))
    skills = models.ManyToManyField(Skill)

    def get_maximum_educational_level(self):
        return max(
            [EducationalLevel(eb.level) for eb in self.educationalbackground_set.all()],
            default=EducationalLevel.OTHERS,
            key=lambda el: el.order_index
        )

    def __str__(self):
        return str(self.user)


class AltEmail(models.Model):
    address = models.EmailField()
    user_profile = models.ForeignKey(UserProfile,
                                     on_delete=models.CASCADE,
                                     related_name="alt_emails")
    verification_token = models.CharField(max_length=50, null=True,
                                          unique=True, db_index=True)
    is_verified = models.BooleanField(default=False)

    def refresh_verification_token(self):
        while True:
            new_verification_token = get_random_string(50)
            try:
                self.verification_token = new_verification_token
                self.save()
                break
            except IntegrityError:
                continue

    def __str__(self):
        return f'{self.user_profile} alt email: {self.address}'


class EducationalBackground(models.Model):
    """
    Each UserProfile can have multiple EducationalBackground instances (OneToMany relationship).
    """
    MIN_YEAR = 1300
    MAX_YEAR = 1450

    field = models.CharField(max_length=80, verbose_name=_('Field'))
    institute = models.CharField(max_length=80, verbose_name=_('Institue'))
    level = models.CharField(max_length=2,
                             choices=EducationalLevel.choices,
                             verbose_name=_('Level'))
    start_year = models.IntegerField(validators=[MinValueValidator(MIN_YEAR),
                                                 MaxValueValidator(MAX_YEAR)],
                                     verbose_name=_('Start year'))
    finish_year = models.IntegerField(validators=[MinValueValidator(MIN_YEAR),
                                                  MaxValueValidator(MAX_YEAR)],
                                      verbose_name=_('Finish year'),
                                      null=False,
                                      blank=True)

    is_currently_studying = models.BooleanField(verbose_name=_('Is currently studying'))
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        _str = ""
        if self.level:
            _str += f" {self.get_level_display()}"
        if self.institute:
            _str += f" @ {self.institute}"
        if self.start_year:
            if get_language() == 'fa':
                _str += f" ({translate_numbers(self.start_year)})"
            else:
                _str += f" ({self.start_year})"
        return _str


class Application(models.Model):

src/jobs/templates/add_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

src/jobs/templates/edit_profile.html
{% extends "dashboard/base_dashboard.html" %}
{% block title %}Edit Profile{% endblock %}
{% load static %}
{% block extra_css %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'jobs/edit_profile.css' %}">
{% endblock %}
{% block main %}
    {% load i18n %}
    {% load extra_tags %}
    {% with request.user.profile as profile %}
        <div class="m">
            {% include 'messages.html' %}
            <h1> {% translate "Edit Profile" %} </h1>
            <hr class="divider">
            <h2> {% translate "Edit Personal Info" %} </h2>
            <form class="form_m" action="{% url 'jobs:edit_profile' %}" method="post">
                {% csrf_token %}
                {% for field in edit_profile_form %}
                    <div class="field {% if field|field_type == 'Textarea' or field.name == "address" %}wide{% endif %}">
                        <label for="email">
                            {{ field.label|title }}
                        </label>
                        {{ field }}
                    </div>
                {% endfor %}
                <input class="grey-black-button edit-button"
                       type="submit"
                       value="{% translate "Edit" %}"
                       name="edit">
            </form>

            <hr class="divider">

            <h2>{% translate "Edit Skills" %}</h2>
            <h3>{% translate "Current Skills" %}</h3>
            <div class="form_m">
                {% for skill in profile.skills.all %}
                    <div class="yt">
                        <div class="info-item__value--tag">
                            {{ skill.title }}
                        </div>
                        <form action="{% url 'jobs:delete_skill' skill.pk %}" method="post">
                            {% csrf_token %}
                            <input class="white-black-button"
                                   type="submit"
                                   value="{% translate 'Delete' %}"
                                   name="delete_skill">
                        </form>
                    </div>
                {% endfor %}
            </div>

            <h3>{% translate "Add new ones" %}</h3>
            <form style="display: flex; flex-direction: column;margin-top: 30px" action="{% url 'jobs:edit_profile' %}"
                  method="post">
                {% csrf_token %}
                {% for field in skill_form %}
                    <div class="field {% if field|field_type == 'Textarea' or field.name == "address" %}wide{% endif %}">
                        <label for="email">
                            {{ field.label }}
                        </label>
                        {{ field }}
                    </div>
                {% endfor %}
                <input class="grey-black-button"
                       style="margin-top: 10px"
                       type="submit"
                       value={% translate "Add" %}
                               name="add_skill">
            </form>

            <hr class="divider" style="margin-top: 50px; margin-bottom: 50px">

            <h2>{% translate "Edit Educational Backgrounds" %}</h2>

            {% for educational_background in profile.educationalbackground_set.all %}
                <div class='educational-background'>
                    <img class="educational-background__institute-logo" src={% static 'images/education.png' %}/>
                    <div class="educational-background__details">
                        <h4 class='info-item__value'>
                            {{ educational_background.field }} | {{ educational_background.institute }}
                        </h4>
                        <h5 class="info-item__value">
                            {{ educational_background.start_year|translate_numbers }}
                            - {{ educational_background.finish_year|translate_numbers }}
                        </h5>
                    </div>
                    <form action="{% url 'jobs:delete_educational_background' educational_background.pk %}"
                          method="get">
                        {% csrf_token %}
                        <input class="grey-black-button"
                               type="submit" name="delete_educational_background" value="{% translate 'delete' %}">
                    </form>
                </div>
            {% endfor %}


            <h3>{% translate "Add new ones" %}</h3>
            <form class="form_m" action="{% url 'jobs:edit_profile' %}" method="post">
                {% csrf_token %}
                {% for field in educational_background_form %}
                    <div class="field {% if field|field_type == 'Textarea' or field.name == "address" %}wide{% endif %}">
                        <label for="email">
                            {{ field.label|title }}
                        </label>
                        {{ field }}
                    </div>
                {% endfor %}
                <input class="grey-black-button edit-button"
                       type="submit"
                       value="{% translate "Add" %}"
                       name="add_educational_background">
            </form>

            <br/>
            <br/>
            <br/>

            <h2> {% translate "Edit Alternative Emails" %} : </h2>

            <h3> {% translate "Edit existing ones" %} </h3>
            <ul>
                {% for email in profile.alt_emails.all %}
                    <li class="alt-email-li">
                        <label>{{ email.address }}</label>
                        <div class="alt-email-li__button-wrapper">
                            <form style="margin: 0 10px;" method="post"
                                  action="{% url 'jobs:delete_alt_email' email.pk %}">
                                {% csrf_token %}
                                <input class="grey-black-button"
                                       type="submit"
                                       value={% translate "Delete" %}>
                            </form>
                            {% if not email.is_verified %}
                                <form method="post"
                                      action="{% url 'jobs:send-email-verification' email_pk=email.pk %}"
                                >
                                    {% csrf_token %}
                                    <button class="grey-black-button"
                                            name="send-verification-email"
                                            value="send-verification-email">
                                        {% translate "Send Verification Email" %}
                                    </button>
                                </form>
                            {% else %}
                                {% translate "Email verified" %}
                                <i class="fa fa-check"></i>
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>

            <h3> {% translate "Add a new email" %} </h3>
            <form class="alt-email-add" method="post" action="{% url 'jobs:add_alt_email' %}">
                {% csrf_token %}
                <div class="field" style="margin-bottom: 10px">
                    <label>
                        {{ alt_email_form.address.label }}
                    </label>
                    {{ alt_email_form.address }}
                </div>
                <input class="grey-black-button"
                       type="submit"
                       value={% translate "Add" %}>
            </form>

        </div>
    {% endwith %}
{% endblock %}

src/jobs/templates/job_offer.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'jobs/company_details.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'jobs/job_offer.css' %}">
{% endblock %}
{% load job_extras %}
{% load cache %}
{% block content %}
    {% load i18n %}
    {% load extra_tags %}

    <div class="company-wrapper">
        <div class="z">
            <div class="section-title">
                <h3>{% translate "Job Information" %}</h3>
            </div>

            <div class="y">
                {% cache 600 JobOffer joboffer.id request.LANGUAGE_CODE %}
                    <h1> {{ joboffer.title }} | {{ joboffer.company.name }} </h1>
                    {% if not joboffer.is_enabled %}
                        <form action="{% url 'jobs:edit_inform_job' joboffer.pk %}" method="get">
                            {% csrf_token %}
                            <input type="submit" value= "{{ inform }}" name="inform">
                        </form>
                    {% endif %}

                    <div class="labeled-info">
                        <h3>{% translate "Description" %}</h3>
                        <h4>{{ joboffer.description|display }}</h4>
                    </div>

                    <div class="labeled-info">
                        <h3>{% translate "Minimum Work Experience Required" %}</h3>
                        <h4>{{ joboffer.minimum_work_experience|translate_numbers }} {% translate "years" %}</h4>
                    </div>

                    <div class="labeled-info">
                        <h3>{% translate "Salary" %}</h3>
                        {% if joboffer.salary is not None %}
                            <h4> {{ joboffer.salary|translate_numbers }} {% translate "IRR" %} </h4>
                        {% else %}
                            {% translate "Not set" %}
                        {% endif %}
                    </div>

                    <div class="labeled-info">
                        <h3>{% translate "Cooperation Type" %}</h3>
                        <h4>{{ joboffer.get_type_of_cooperation_display|title }}</h4>
                    </div>

                    <div class="labeled-info">
                        <h3>{% translate "Minimum Degree Required" %}</h3>
                        {{ joboffer.get_minimum_degree_display|display }}
                    </div>

                    <div class="labeled-info">
                        <h3>{% translate "Required Skills" %}</h3>
                        {% if joboffer.skills_required.all %}
                            <div class='skill-tag-wrapper'>
                                {% for skill in joboffer.skills_required.all %}
                                    <h4 class='skill-tag'> {{ skill }} </h4>
                                {% endfor %}
                            </div>
                        {% else %}
                            <h4>{% translate "No Skill is specified." %}</h4>
                        {% endif %}
                    </div>
                {% endcache %}

                {% with request.user as user %}
                    {% if not user.profile %}
                        <div class="error_box">
                            {% translate "You need to complete your profile before applying for a job." %}
                        </div>
                    {% else %}
                        {% with user|get_applications_for_offer:joboffer as applications %}
                            {% if applications %}
                                <h4>
                                    {% translate "Your Applications History for This Job" %}</h4>
                                <ol>
                                    {% for application in applications|dictsort:"created_at" %}
                                        <li>{% translate "Applied on " %} {{ application.created_at|date:'d M Y' }}|
                                            {% translate "Result" %}: {{ application.get_state_display }}
                                            {% if application.reject_reason %}
                                                <p>{% translate "Reason" %}: {{ application.reject_reason }}</p>
                                            {% endif %}
                                        </li>
                                    {% endfor %}
                                </ol>
                            {% endif %}
                        {% endwith %}
                        {% if not joboffer.is_enabled %}
                            <div class="error_box">
                                {% translate "This Job is currently Disabled." %}
                            </div>
                        {% elif not user|has_pending_application_for_offer:joboffer %}
                            <form class="apply"
                                  method="post"
                                  action=" {% url 'jobs:apply' joboffer.pk %}"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                {#                                <label> Upload your resume </label>#}
                                {#                                <input type="file" name="resume" class="white-button">#}
                                <label for="file-upload" class="custom-file-upload">
                                    {% translate "Upload your resume" %}
                                </label>
                                <input id="file-upload" type="file"/>
                                <button class="purple-grey-button" type="submit">
                                    {% translate "APPLY FOR THIS JOB" %}
                                </button>
                            </form>
                        {% endif %}
                    {% endif %}
                    {% include 'messages.html' %}
                {% endwith %}
            </div>

        </div>

        <hr class="divider"/>

        <div style="
                    display: flex;
                    flex-direction: column;
                     align-items: center;
                     justify-content: center;
                     margin-top: 50px;
                     margin-bottom: 50px;
                    ">
            <h3 style="margin: 0 auto">

                <a style="color: purple" href="{% url 'jobs:main' %}#paginated_section">
                    {% translate "Browse other job openings" %}
                </a>
                {% translate "or" %}
                <a style="color: purple" href={% url 'jobs:company' joboffer.company.pk %}>
                    {% translate "visit company page" %}
                </a>
            </h3>
        </div>

    </div>

{% endblock %}

src/jobs/templates/pdf_template.html
<!DOCTYPE html>
<pdf:language name="persian"/>
<html lang="fa" dir="rtl">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>

  <style>
    @font-face {
      font-family: IRANSansX;
      src: url('assets/IRANSansX-Regular.ttf');
      font-weight: 400;
    }
    html {
      font-family: sans-serif, IRANSansX, serif;
    }
    @font-face {
      font-family: IRANSansX;
      src: url('assets/IRANSansX-Bold.ttf');
      font-weight: 700;
    }

  </style>
  <body class="body">
    <aside>
      <section>
        <h1 class="mb-3">{{ user.first_name }} {{ user.last_name }}</h1>

        {% if user.profile.bio %}
          <p class="mb-3">
            {{ user.profile.bio }}
          </p>
        {% endif %}

        {% if user.email %}
          <h4 class="mb-1">راه های ارتباطی</h4>
        {% endif %}

        <ul class="mb-3">
          {% if user.email %}
            <li class="mb-1">
              <a href="mailto:{{user.email}}">
                {{ user.email }}
              </a>
            </li>
          {% endif %}

          {% if user.profile.phone_number %}
            <li class="mb-1">
              <a href="tel:{{ user.profile.phone_number }}">{{ user.profile.phone_number }}</a>
            </li>
          {% endif %}

          {% if user.profile.mobile_number %}
            <li class="mb-1">
              <a href="tel:{{ user.profile.mobile_number }}">{{ user.profile.mobile_number }}</a>
            </li>
          {% endif %}
        </ul>

        <ul>
          {% if user.profile.city_of_residence %}
            <li class="mb-2">
              <h4>شهر محل سکونت:</h4>
              <p>{{ user.profile.city_of_residence }}</p>
            </li>
          {% endif %}

          {% if user.profile.address %}
            <li class="mb-2">
              <h4>آدرس:</h4>
              <p>{{ user.profile.address }}</p>
            </li>
          {% endif %}

          {% if user.profile.marital_status %}
            <li class="mb-2">
              <h4>وضعیت تاهل:</h4>
              <p>{{ user.profile.get_marital_status_display }}</p>
            </li>
          {% endif %}

          {% if user.profile.military_service %}
            <li class="mb-2">
              <h4>وضعیت نظام وظیفه:</h4>
              <p>{{ user.profile.get_military_service_status_display }}</p>
            </li>
          {% endif %}

          {% if user.profile.skills.all %}
            <li>
              <h4>مهارت ها</h4>
              <ul>
                {% for skill in user.profile.skills.all %}
                  <li> {{ skill.title }}</li>
                {% endfor %}
              </ul>
            </li>
          {% endif %}

        </ul>
      </section>
    </aside>
    <main>
      {% if user.profile.educationalbackground_set.all %}
        <section>
          <h4 class="mb-1">سوابق تحصیلی</h4>
          <div class="hr" />
          <ul>
            {% for educational_background in user.profile.educationalbackground_set.all %}
              <li>
                <h4> {{ educational_background.institute }} </h4>
                <p> {{ educational_background.field }} - {{ educational_background.get_level_display }} </p>
                <p> {{ educational_background.start_year }} - {% if educational_background.is_currently_studying %} مشغول به تحصیل {% else %} {{ educational_background.finish_year }} {% endif %} </p>
              </li>
            {% endfor %}
          </ul>
        </section>
      {% endif %}
    </main>
  </body>
</html>