src/authentication/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'auth'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.login_user, name='login'),
    path('send-email-verification/', views.send_email_verification, name='send-email-verification'),
    path('verify/<str:token>/', views.verify_email, name='verify'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset/', views.CustomPasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         views.CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-done/',
         views.CustomPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-complete/',
         views.CustomPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

src/jobs/urls.py
from django.urls import path

from jobs import views

app_name = 'jobs'
urlpatterns = [
    # ex: /job_offers/5
    path('job_offers/<int:pk>/', views.JobOffersView.as_view(), name='job_offers'),
    path('', views.MainView.as_view(), name='main'),
    path('profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('company/<int:pk>/', views.CompanyView.as_view(), name='company'),
    # ex: /edit_profile
    path('edit_profile/', views.edit_profile_view, name='edit_profile'),
    # ex: /edit_profile/delete_skill/5
    path('edit_profile/delete_skill/<skill_id>/', views.delete_skill, name='delete_skill'),
    # ex: /edit_profile/delete_educational_background/5
    path('edit_profile/delete_educational_background/<educational_background_id>/',
         views.delete_educational_background, name='delete_educational_background'),
    path('edit_profile/alt_email/add/', views.add_alt_email, name='add_alt_email'),
    path('edit_profile/alt_email/delete/<int:alt_email_pk>/',
         views.delete_alt_email,
         name='delete_alt_email'),
    path('send-email-verification/<int:email_pk>/',
         views.send_email_verification,
         name='send-email-verification'),
    path('verify/<str:token>/', views.verify, name='verify'),
    # ex: /job_offers/5/apply
    path('job_offers/<int:pk>/apply/', views.apply, name='apply'),
    path('create_resume/', views.create_resume, name='create_resume'),
    path('edit_inform_joboffer/<int:job_offer_pk>/', views.edit_inform_jobOffer, name='edit_inform_job')

]

src/website/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('i18n/set_language/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('jobs.urls')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = 'website.views.error_404'

templates/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/messages.css' %}">
    {% block extra_css %}
    {% endblock %}
    {% if LANGUAGE_CODE == 'fa' %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/rtl.css' %}">
    {% endif %}
    <title>{% block title %}Hezardastan Careers{% endblock %}</title>
</head>
<body dir="auto">
{% block navbar %}
    <nav class="nav app__header">
        <ul class="nav__ul">
            <li>
                <div class="home-anchor-wrapper">
                    <a class="home-anchor" href="/">
                        <img class="nav__logo" src="{% static '/images/HezardastanLogo.png' %}" alt=""/>
                    </a>
                </div>
            </li>
            <li><a href={% url 'jobs:main' %}>{% translate 'Home' %}</a></li>
            <li><a href="{% url 'jobs:main' %}#companies">{% translate 'Companies' %} </a></li>
            <li><a href="{% url 'jobs:main' %}#paginated_section">{% translate 'Job Openings' %} </a></li>
            {% if request.user.is_authenticated %}
                <li><a href={% url 'jobs:user_profile' %}>
                    <img class="nav__profile-photo" src="{% static '/images/profile.png' %}" alt=""/>
                </a></li>
            {% else %}
                <li><a href="{% url 'auth:login' %}">{% translate 'Login' %} </a></li>
            {% endif %}
            <li>
                <form action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% if LANGUAGE_CODE == "fa" %}
                        <input class="lang-button" type="submit" value="en" name="language">
                    {% else %}
                        <input class="lang-button" type="submit" value="fa" name="language">
                    {% endif %}
                </form>
            </li>
        </ul>
    </nav>
{% endblock %}
<div class="app__content">
    {% block content %}{% endblock content %}
</div>

<footer class="footer app__footer" }>
    <p class="footer__text">
        {% translate "Hezardastan Information Technology Development Group" %}©
    </p>
</footer>
</body>
</html>