src/authentication/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'auth'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.login_user, name='login'),
    path('send-email-verification/', views.send_email_verification, name='send-email-verification'),
    path('verify/<str:token>/', views.verify_email, name='verify'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-reset/', views.CustomPasswordResetView.as_view(),
         name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/',
         views.CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-done/',
         views.CustomPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-complete/',
         views.CustomPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

src/jobs/urls.py
from django.urls import path

from jobs import views

app_name = 'jobs'
urlpatterns = [
    # ex: /job_offers/5
    path('job_offers/<int:pk>/', views.JobOffersView.as_view(), name='job_offers'),
    path('', views.MainView.as_view(), name='main'),
    path('profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('company/<int:pk>/', views.CompanyView.as_view(), name='company'),
    # ex: /edit_profile
    path('edit_profile/', views.edit_profile_view, name='edit_profile'),
    # ex: /edit_profile/delete_skill/5
    path('edit_profile/delete_skill/<skill_id>/', views.delete_skill, name='delete_skill'),
    # ex: /edit_profile/delete_educational_background/5
    path('edit_profile/delete_educational_background/<educational_background_id>/',
         views.delete_educational_background, name='delete_educational_background'),
    path('edit_profile/alt_email/add/', views.add_alt_email, name='add_alt_email'),
    path('edit_profile/alt_email/delete/<int:alt_email_pk>/',
         views.delete_alt_email,
         name='delete_alt_email'),
    path('send-email-verification/<int:email_pk>/',
         views.send_email_verification,
         name='send-email-verification'),
    path('verify/<str:token>/', views.verify, name='verify'),
    # ex: /job_offers/5/apply
    path('job_offers/<int:pk>/apply/', views.apply, name='apply'),
    path('create_resume/', views.create_resume, name='create_resume'),
    path('edit_inform_joboffer/<int:job_offer_pk>/', views.edit_inform_jobOffer, name='edit_inform_job')

]

src/website/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = i18n_patterns(
    path('i18n/set_language/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('', include('jobs.urls')),
    prefix_default_language=False
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler404 = 'website.views.error_404'

src/authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager
from django.db import IntegrityError
from django.utils.crypto import get_random_string
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(verbose_name=_('email address'),
                              unique=True,
                              error_messages={
                                  'unique': _("A user with that email already exists."),
                              },
                              )

    verification_token = models.CharField(max_length=50, null=True, unique=True, db_index=True)
    is_email_verified = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def refresh_verification_token(self):
        while True:
            new_verification_token = get_random_string(50)
            try:
                self.verification_token = new_verification_token
                self.save()
                break
            except IntegrityError:
                continue

    def __str__(self):
        if self.first_name or self.last_name:
            return self.get_full_name()
        else:
            return self.email

    def has_pending_application_for_offer(self, offer):
        from jobs.models import Application
        return offer.applications.filter(user=self, state=Application.State.PENDING).exists()

    def get_applications_for_offer(self, offer):
        return offer.applications.filter(user=self)

    def has_skills_for_offer(self, offer):
        shortage_skills = offer.skills_required.all().exclude(
            pk__in=self.profile.skills.all())
        if len(shortage_skills) == 0:
            return True
        return False

    def has_education_for_offer(self, offer):
        from jobs.models import EducationalLevel
        if offer.minimum_degree is None:
            return True

        user_educational_background = self.profile.educationalbackground_set
        acceptable_levels = EducationalLevel(offer.minimum_degree).get_ge_educational_levels()

        return user_educational_background.filter(level__in=acceptable_levels).exists()

    def has_requirement_for_offer(self, offer):
        if self.profile.city_of_residence != offer.city:
            return False
        if not self.has_skills_for_offer(offer):
            return False
        if not self.has_education_for_offer(offer):
            return False
        return True

src/authentication/forms.py
from jobs.models import UserProfile
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):
    class Meta:
        fields = ['first_name', 'last_name', 'email']
        model = CustomUser

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        if commit:
            user.save()
            UserProfile(user=user).save()
        return user

src/authentication/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView
from authentication.models import CustomUser
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView
from .forms import UserForm


class RegisterView(SuccessMessageMixin, CreateView):
    model = CustomUser
    template_name = 'register.html'
    form_class = UserForm
    success_url = settings.LOGIN_URL
    success_message = _("Your account has been created successfully.")


def login_user(request):
    if request.method == 'GET':
        return HttpResponse(render(request, 'login.html'))
    if request.method == 'POST':
        context = {}

        if request.POST.get('email') and request.POST.get('password'):
            user = authenticate(
                request,
                email=request.POST['email'],
                password=request.POST['password']
            )
        else:
            context['error'] = _('Email and password must be provided.')
            return render(request, 'login.html', context, status=200)

        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return HttpResponseRedirect(request.POST.get('next'))
            return HttpResponseRedirect(reverse('jobs:main'))
        else:
            context['error'] = _('Wrong credentials.')
            return render(request, 'login.html', context, status=200)


@login_required
def send_email_verification(request):
    if request.method != "POST":
        return HttpResponse("Bad request (This url only accepts post requests)", status=400)

    if request.user.is_email_verified:
        return HttpResponse('Your email is already verified!')

    user = request.user
    user.refresh_verification_token()

    domain = get_current_site(request).domain
    mail_subject = 'Activate your Adams account.'
    token = user.verification_token
    message = render_to_string('email_templates/verification-email.html', {
        'user': request.user,
        'domain': domain,
        'token': token,
    })
    to_email = request.user.email
    email = EmailMessage(
        mail_subject, message, to=[to_email]
    )
    email.send()
    messages.success(request, f"Verification email sent to {request.user.email}")

    return HttpResponseRedirect(reverse("jobs:user_profile"))


def verify_email(request, token):
    try:
        user = CustomUser.objects.get(verification_token=token)

        user.verification_token = None
        user.is_email_verified = True
        user.save()
        messages.success(request, 'Thank you for your email confirmation.')
        return HttpResponseRedirect('/')

    except CustomUser.DoesNotExist:
        return HttpResponse('Verification link is invalid!')


class CustomPasswordResetView(PasswordResetView):
    email_template_name = 'email_templates/password_reset_email.html'
    template_name = 'password_reset.html'
    success_url = reverse_lazy('auth:password_reset_done')


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'password_reset_confirm.html'
    success_url = reverse_lazy('auth:password_reset_complete')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'password_reset_done.html'


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'password_reset_complete.html'

src/authentication/templates/login.html
{% extends 'login_register_base.html' %}
{% load static %}
{% block side %}
    {% load i18n %}
    <div class="side-wrapper">
        {% include 'messages.html' %}
        <div class="side">
            <h1 class="side__title">{% translate "Sign in to your account" %}</h1>
            <h5 class="side__alter-message">
                <a class="purple-link" href={% url 'auth:register' %}>
                    {% translate "Don't have an account? Create one here" %}
                </a>
            </h5>

            <h5>{% translate "Sign in with" %}</h5>
            <div class="button__wrapper">
                <button class="grey-transparent-button auth-method-button">
                    <i class="fa fa-google"></i>
                </button>

                <button class="grey-transparent-button auth-method-button">
                    <i class="fa fa-linkedin"></i>
                </button>
            </div>

            <h2 class="continue-with"><span>
                {% translate "Or continue with" %}
            </span></h2>

            {% if error %}
                <span class="error_box"> {{ error }} </span>
            {% endif %}

            <form class="side__form" action="{% url 'auth:login' %}" method="post">
                {% csrf_token %}
                <span class="input-field-wrapper">
                        <label class="form__label" for="email">
                            {% translate "Email address" %}
                        </label>
                        <input class="form__text-input" type="text" id="email" name="email"/>
                </span>

                <span class="input-field-wrapper">
                        <label class="form__label" for="password">
                            {% translate "Password" %}
                        </label>
                        <input class="form__text-input" type="password"
                               id="password" name="password"/>
                </span>

                <span class="remember-me-wrapper">
                        <span>
                            <input type="checkbox" id="remember-me" name="remember-me"/>
                            <label for="remember-me">{% translate "Remember me" %}</label>
                        </span>
                        <a class="purple-link" href="{% url 'auth:password_reset' %}">
                            {% translate "Forgot your password?" %}
                        </a>
                </span>

                <span class="input-field-wrapper">
                        <button class="grey-transparent-button" id="login-button">
                            {% translate "Login" %}
                        </button>
                </span>
            </form>
            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}">
                {% get_current_language as LANGUAGE_CODE %}
                {% if LANGUAGE_CODE == "fa" %}
                    <input class="lang-button" type="submit" value="en" name="language">
                {% else %}
                    <input class="lang-button" type="submit" value="fa" name="language">
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

src/authentication/templates/login_register_base.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'authentication/login-register.css' %}">
{% endblock %}
{% block navbar %}
{% endblock %}
{% block content %}
    {% load i18n %}
    <div class="login_register">
        {% block side %}
        {% endblock %}

        <div class="background">
            <img class="background__logo" src="{% static 'images/hezardastanLogoTransient.svg' %}"/>
            <span class="background__wrapper">
            <h1 class="background__title">
                {% translate "Hezardastan Development Group Career System" %}
            </h1>
        </span>
        </div>
    </div>
{% endblock %}

src/authentication/templates/password_reset.html
{% load i18n %}
<h1> {% translate 'Trouble Signing In?' %}<br>
    <span> {% translate 'request a password reset, and we will have you up again..' %}</span>
</h1>
<form method='post'>
    {%csrf_token%}
    {{form}}
    <input type="submit" value= {% translate "forgotten password"  %} class="submit-btn">
</form>

<small class="text-muted">
    {% translate "try signing in again?" %}  <a class="ml-2" href="{% url 'auth:login' %}"> {% translate "Log Into Your Account" %}</a>
</small>

src/authentication/templates/password_reset_complete.html
{% load i18n %}


<p>{% translate "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% translate 'Log in' %}</a></p>

src/authentication/templates/password_reset_confirm.html
{% load i18n %}

{% if validlink %}

    <p>{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

    <form method="post">{% csrf_token %}
        <fieldset class="module aligned">
            <input class="hidden" autocomplete="username" value="{{ form.user.get_username }}">
            <div class="form-row field-password1">
                {{ form.new_password1.errors }}
                <label for="id_new_password1">{% translate 'New password:' %}</label>
                {{ form.new_password1 }}
            </div>
            <div class="form-row field-password2">
                {{ form.new_password2.errors }}
                <label for="id_new_password2">{% translate 'Confirm password:' %}</label>
                {{ form.new_password2 }}
            </div>
            <input type="submit" value="{% translate 'Change my password' %}">
        </fieldset>
    </form>

{% else %}

    <p>{% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}


<form action={% url 'auth:login' %}  method="get">
    <input type="submit" value="Go to LOGIN page">
</form>

src/authentication/templates/password_reset_done.html
{% load i18n %}

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

<form action= {% url 'auth:login' %}  method="get">
    <input type="submit" value="Go to LOGIN page">
</form>

src/authentication/templates/register.html
{% extends 'login_register_base.html' %}
{% load static %}
{% load filters %}
{% block side %}
    {% load i18n %}
    <div class="side-wrapper">
        <div class="side">
            <h1 class="side__title"> {% translate "Create an account" %} </h1>
            <h5 class="side__alter-message">
                <a class="purple-link" href="{% url 'auth:login' %}">
                    {% translate "Already have an account? Sign in here" %}
                </a>
            </h5>

            <h5>{% translate "Create an account with" %}</h5>
            <div class="button__wrapper">
                <button class="grey-transparent-button auth-method-button">
                    <i class="fa fa-google"></i>
                </button>

                <button class="grey-transparent-button auth-method-button">
                    <i class="fa fa-linkedin"></i>
                </button>
            </div>

            <h2 class="continue-with"><span>
                {% translate "Or continue with" %}
            </span></h2>

            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <span class="error_box">
                            {{ field.label }}: {{ error|escape }}
                        </span>
                    {% endfor %}
                {% endfor %}
            {% endif %}

            <form class="side__form" action="{% url 'auth:register' %}" method="post">
                {% csrf_token %}
                <span class="input-field-wrapper">
                    <label class="form__label" for="email">
                        {% translate "Email address" %}
                    </label>
                    {{ form.email|addclass:'form__text-input' }}
                </span>

                <span class="dual-input-row">
                    <span class="input-field-wrapper">
                        <label class="form__label" for="password">
                            {% translate "First Name" %}
                        </label>
                        {{ form.first_name|addclass:'form__text-input' }}
                    </span>

                    <span class="input-field-wrapper">
                        <label class="form__label" for="password">
                            {% translate "Last Name" %}
                        </label>
                        {{ form.last_name|addclass:'form__text-input' }}
                    </span>
                </span>

                <span class="dual-input-row">
                    <span class="input-field-wrapper">
                        <label class="form__label" for="password">
                            {% translate "Password" %}
                        </label>
                        {{ form.password1|addclass:'form__text-input' }}
                    </span>
                    <span class="input-field-wrapper">
                        <label class="form__label" for="password">
                            {% translate "Password (again)" %}</label>
                        {{ form.password2|addclass:'form__text-input' }}
                    </span>
                </span>

                <span class="input-field-wrapper">
                    <button class="grey-transparent-button" id="login-button">
                        {% translate "Register" %}
                    </button>
                </span>
            </form>
            <form action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}">
                {% get_current_language as LANGUAGE_CODE %}
                {% if LANGUAGE_CODE == "fa" %}
                    <input class="lang-button" type="submit" value="en" name="language">
                {% else %}
                    <input class="lang-button" type="submit" value="fa" name="language">
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}